name: Syntax Checks

on: [ push, pull_request, workflow_dispatch ]

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        php: ["8.0", "8.1"]

    name: Syntax Checks Under PHP ${{ matrix.php }}

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Run Syntax Checks
        run: |
          docker run --rm -v "$(pwd):/project" -w /project -i jakzal/phpqa:php${{ matrix.php }} phplint src
